name: Build Docker Image

on:
  push:
    branches:
      - main # Adjust to the branch you want to trigger the build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub (optional, if pushing to a registry)
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Build and push the Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          # platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

      - name: Deploy to kimlineclinic
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.HOSTS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            cd kimlineclinic
            docker pull ghcr.io/${{ github.repository }}:latest
            docker compose -f docker-compose.prod.yml up -d
